name: Deploy win/mac wheels (wip)

on:
  workflow_dispatch:
    inputs:
      wip:
        description: 'Publish work in progress package.'
        required: false
        default: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - windows-2016
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip prerequisites
      run: |
        pip install --user cffi scikit-build cmake ninja twine

    - name: Install macos-10.15 prerequisites
      if: ${{ matrix.os == 'macos-10.15' }}
      run: |
        brew update
        brew install re2c
        brew install bison@2.7

    - name: Install windows-2016 prerequisites
      if: ${{ matrix.os == 'windows-2016' }}
      run: |
        choco install re2c
        choco install winflexbison3

    - name: Compile and upload wheels (wip)
      if: ${{ github.event.inputs.wip }}
      run: python .github/pipwinmac.py
      env:
        TWINE_NON_INTERACTIVE: True
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Compile and upload wheels (release)
      if: ${{ !github.event.inputs.wip }}
      run: python .github/pipwinmac.py --release
      env:
        TWINE_NON_INTERACTIVE: True
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_RELEASE }}
