name: Deploy ppa package (wip)

on:
  workflow_dispatch:
    inputs:
      wip:
        description: 'Publish work in progress package.'
        required: false
        default: 'true'

jobs:
  build_packages:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [jammy, focal, bionic]

    env:
      distribution: ${{ matrix.distribution }}

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install pbuilder pbuilder-scripts debootstrap devscripts dh-make dput dh-python

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup gpg
      run: |
        echo "$POTASSCO_PPA_GPGKEY" | base64 --decode | gpg --batch --import
      env:
        POTASSCO_PPA_GPGKEY: ${{ secrets.POTASSCO_PPA_GPGKEY }}

    - name: Build deb and source package (wip)
      if: ${{ github.event.inputs.wip == 'true' }}
      run: |
        cd .github/ppa-wip
        ./build.sh wip "$distribution" create sync changes build put

    - name: Build deb and source package (release)
      if: ${{ github.event.inputs.wip == 'false' }}
      run: |
        cd .github/ppa-wip
        ./build.sh stable "$distribution" create sync changes build put
